version: 2

models:
  - name: products_with_lowest_profit_margins
    description: '{{ doc("products_with_lowest_profit_margins_query_description") }}'
    
    columns:
          - name: product_id
            description: "ID of the Product."

          - name: product_name
            description: "Name of the Product."

          - name: total_orders
            description: "Number of distinct orders pertaining to each product."

          - name: total_products_purchased
            description: "Number of products purchased."

          - name: profit_margin
            description: "Profit margin pertaining to each product."


         
  
          